export const UPDATE_SCREEN_CONTENTS = 'UPDATE_SCREEN_CONTENTS';
export const TOGGLE_KEY_INPUT = 'TOGGLE_KEY_INPUT';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const START_LOCKING = 'START_LOCKING';
export const UPDATE_LOCKED_INDICATOR = 'UPDATE_LOCKED_INDICATOR';
export const UPDATE_STATE = 'UPDATE_STATE';
export const DISPLAY_STATE = 'DISPLAY_STATE';
export const FETCH_SERIAL_NUMBER = 'FETCH_SERIAL_NUMBER';
