export const UPDATE_SCREEN_CONTENTS = 'UPDATE_SCREEN_CONTENTS';
export const TOGGLE_KEY_INPUT = 'TOGGLE_KEY_INPUT';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const VERIFY_PASSWORD = 'VERIFY_PASSWORD';
export const CHANGE_STATE = 'CHANGE_STATE';
export const DISPLAY_STATE = 'DISPLAY_STATE';
export const FETCH_SERIAL_NUMBER = 'FETCH_SERIAL_NUMBER';
